<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BackendVsaOwin.BuildingBlocks.Persistence</RootNamespace>
    <AssemblyName>BackendVsaOwin.BuildingBlocks.Persistence</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
