<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BackendVsaOwin.Host</RootNamespace>
    <AssemblyName>BackendVsaOwin.Host</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BackendVsaOwin.BuildingBlocks.WebApi\BackendVsaOwin.BuildingBlocks.WebApi.csproj" />
    <ProjectReference Include="..\..\Modules\BackendVsaOwin.Modules.Customers\BackendVsaOwin.Modules.Customers.csproj" />
    <ProjectReference Include="..\..\Modules\BackendVsaOwin.Modules.Orders\BackendVsaOwin.Modules.Orders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Owin" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Owin" />
    <PackageReference Include="Microsoft.Owin.Host.HttpListener" />
    <PackageReference Include="Microsoft.Owin.Hosting" />
    <PackageReference Include="Microsoft.Owin.Security" />
    <PackageReference Include="Microsoft.Owin.Security.OAuth" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NJsonSchema.NewtonsoftJson" />
    <PackageReference Include="NSwag.AspNet.Owin" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>
